const SET_STATE= "SET_STATE"
const GET_PRODUCTS = 'GET_PRODUCTS'
const PRODUCT_DETAIL = 'PRODUCT_DETAIL'
const POST_PRODUCT = 'POST_PRODUCT'
const OPEN_FILTERS = 'OPEN_FILTERS'
const ORDER_BY = 'ORDER_BY'
const FILTER = 'FILTER'
const SEARCH= 'SEARCH'
const GET_BRANDS = 'GET_BRANDS'
const BRAND_ELECT = 'BRAND_ELECT'
const GET_COLORS = 'GET_COLORS'
const GET_CATEGORIES = 'GET_CATEGORIES'

export{
    SET_STATE,
    GET_PRODUCTS,
    PRODUCT_DETAIL,
    POST_PRODUCT,
    OPEN_FILTERS,
    ORDER_BY,
    FILTER,
    SEARCH,
    GET_BRANDS,
    BRAND_ELECT,
    GET_COLORS,
    GET_CATEGORIES,
}
///