const SET_STATE= "SET_STATE"
const GET_PRODUCTS = 'GET_PRODUCTS'
const PRODUCT_DETAIL = 'PRODUCT_DETAIL'
const CLEAR_DETAIL = 'CLEAR_DETAIL'
const PRODUCT_UPDATE = 'PRODUCT_UPDATE'
const POST_PRODUCT = 'POST_PRODUCT'
const SEARCH = 'SEARCH'
const GET_CATEGORIES = 'GET_CATEGORIES'
const GET_BRANDS = 'GET_BRANDS'
const GET_COLORS = 'GET_COLORS'
const GET_ADMINS = 'GET_ADMINS'
const GET_USERS = 'GET_USERS'
const GET_PROFILE = 'GET_PROFILE'
const GET_CURRENT_USER = 'GET_CURRENT_USER'
const UPDATE_USER = 'UPDATE_USER'
const UPDATE_USER_ADM = 'UPDATE_USER_ADM'
const POST_USER = 'POST_USER'
export{
    SET_STATE,
    GET_PRODUCTS,
    PRODUCT_DETAIL,
    CLEAR_DETAIL,
    PRODUCT_UPDATE,
    POST_PRODUCT,
    SEARCH,
    GET_CATEGORIES,
    GET_BRANDS,
    GET_COLORS,
    GET_ADMINS,
    GET_USERS,
    GET_PROFILE,
    GET_CURRENT_USER,
    UPDATE_USER,
    UPDATE_USER_ADM,
    POST_USER,
    
    
}